//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETGIOHANG
    {
        public int ID { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> IDGH { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public Nullable<int> UnitPrice { get; set; }
    
        public virtual GIOHANG GIOHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
