//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETLUONGNHANVIEN
    {
        public int ID { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> TONGGIOCONG { get; set; }
        public Nullable<int> THANHTIEN { get; set; }
        public string KYLUONG { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
