//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongThuc
    {
        public int IDCT { get; set; }
        public Nullable<int> MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> IDNL { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string DonVi { get; set; }
    
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
