//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIOHANG()
        {
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> IDKH { get; set; }
        public Nullable<decimal> Trigia { get; set; }
        public string AddressDeliverry { get; set; }
        public Nullable<bool> Dagiao { get; set; }
        public Nullable<System.DateTime> Ngaygiaohang { get; set; }
        public string TenNguoiNhan { get; set; }
        public Nullable<int> DienThoaiNhan { get; set; }
        public Nullable<bool> TTrang { get; set; }
        public Nullable<int> HTGiaoHang { get; set; }
        public Nullable<int> HTThanhToan { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
