//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.HOADONs = new HashSet<HOADON>();
            this.LISTLOVEs = new HashSet<LISTLOVE>();
        }
    
        public int IDKH { get; set; }
        public string TenKH { get; set; }
        public int MALKH { get; set; }
        public string DiaChiKH { get; set; }
        public Nullable<int> SDTKH { get; set; }
        public string EmailKH { get; set; }
        public string PassKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTLOVE> LISTLOVEs { get; set; }
        public virtual LOAIKHACHHANG LOAIKHACHHANG { get; set; }
    }
}
