//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEUKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUYENLIEUKHO()
        {
            this.CHITIETHOADONNHAPXUATs = new HashSet<CHITIETHOADONNHAPXUAT>();
        }
    
        public int IDNLKHO { get; set; }
        public string TENNLKHO { get; set; }
        public int IDLNL { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<int> IDKHO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADONNHAPXUAT> CHITIETHOADONNHAPXUATs { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual LOAINGUYENLIEU LOAINGUYENLIEU { get; set; }
    }
}
