//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CHITIETLUONGNHANVIENs = new HashSet<CHITIETLUONGNHANVIEN>();
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int IDNV { get; set; }
        public string HOVATEN { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public int SDT { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string CHUCVU { get; set; }
        public double MUCLUONG { get; set; }
        public string PASSWORD { get; set; }
        public string DiaChiCH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETLUONGNHANVIEN> CHITIETLUONGNHANVIENs { get; set; }
        public virtual CUAHANG CUAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
