//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.CongThucs = new HashSet<CongThuc>();
            this.LISTLOVEs = new HashSet<LISTLOVE>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> LOAISP { get; set; }
        public Nullable<int> IDNL { get; set; }
        public Nullable<int> SLUONG { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> GIASP { get; set; }
        public string DiaChiCH { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongThuc> CongThucs { get; set; }
        public virtual CUAHANG CUAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTLOVE> LISTLOVEs { get; set; }
        public virtual LOAISP LOAISP1 { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
