//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class TINTUC
    {
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string HinhAnhTieuDe { get; set; }
        public int IDTINTUC { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
